# Generated by Django 2.2.6 on 2019-11-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191104_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
