# Generated by Django 2.2.7 on 2019-11-21 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('required_age', models.FloatField(default=0.0)),
                ('required_gender', models.CharField(default='None', max_length=6)),
                ('stimulate_phase', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('required_age', models.FloatField(default=0.0)),
                ('required_gender', models.CharField(default='None', max_length=6)),
                ('stimulate_phase', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_count', models.IntegerField(default=1)),
                ('dose_duration', models.IntegerField(default=0)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.VaccineModel')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_count', models.IntegerField(default=1)),
                ('dose_duration', models.IntegerField(default=0)),
                ('date_expired', models.DateField(blank=True, null=True)),
                ('received', models.BooleanField(default=False)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.Vaccine')),
            ],
        ),
    ]
