# Generated by Django 2.2.7 on 2019-11-26 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='taken_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
