# Generated by Django 2.2.7 on 2019-12-06 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('recommend_vaccine', models.CharField(max_length=50)),
                ('added_date', models.DateField(default=datetime.date)),
            ],
        ),
    ]
