# Generated by Django 2.2.6 on 2019-11-11 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('required_age', models.FloatField(default=0.0)),
                ('required_gender', models.CharField(default='None', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='vaccine',
            name='required_gender',
            field=models.CharField(default='None', max_length=6),
        ),
        migrations.AlterField(
            model_name='dose',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.VaccineModel'),
        ),
    ]
