# Generated by Django 2.2.7 on 2019-12-06 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_outbreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbreak',
            name='added_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
