# Generated by Django 2.2.6 on 2019-11-11 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_auto_20191111_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.Vaccine'),
        ),
        migrations.CreateModel(
            name='DoseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_count', models.IntegerField(default=1)),
                ('dose_duration', models.IntegerField(default=0)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.VaccineModel')),
            ],
        ),
    ]
