# Generated by Django 2.2.7 on 2019-11-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_vaccine_taken_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='taken_date',
        ),
    ]
