# Generated by Django 2.2.6 on 2019-11-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0003_auto_20191111_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='date_expired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
