# Generated by Django 2.2.7 on 2019-11-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_dose_date_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinemodel',
            name='stimulate_phase',
            field=models.IntegerField(default=0),
        ),
    ]
