# Generated by Django 2.2.7 on 2019-11-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0005_vaccinemodel_stimulate_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='stimulate_phase',
            field=models.IntegerField(default=0),
        ),
    ]
