# Generated by Django 2.2.7 on 2019-11-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0006_auto_20191121_0259'),
        ('vaccine', '0006_auto_20191121_0346'),
    ]

    operations = [
    ]
