# Generated by Django 2.2.7 on 2019-11-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0007_merge_20191121_0609'),
        ('vaccine', '0007_merge_20191121_0458'),
    ]

    operations = [
    ]
