# Generated by Django 2.2.6 on 2019-10-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_surname', models.CharField(max_length=30)),
                ('user_gender', models.BooleanField(default=True)),
                ('user_tel', models.CharField(max_length=10)),
                ('user_birthday', models.DateField()),
                ('user_contact', models.CharField(default='', max_length=30)),
                ('user_emer_contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('vaccine_taken_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_count', models.IntegerField(default=1)),
                ('dose_duration', models.IntegerField(default=0, help_text='Enter duration count as day')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacseenApp.Vaccine')),
            ],
        ),
    ]
