# Generated by Django 2.2.6 on 2019-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacseenApp', '0002_remove_vaccine_vaccine_taken_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='dose_duration',
            field=models.IntegerField(default=0),
        ),
    ]
