# Generated by Django 2.2.6 on 2019-11-02 08:54

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacseenApp', '0004_auto_20191102_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsmodel',
            name='credential',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True),
        ),
    ]
